--[[
	BEGOTTEN III: Developed by DETrooper, cash wednesday, gabs & alyousha35
--]]

PLUGIN:SetGlobalAlias("cwStorage")

util.Include("cl_plugin.lua")
util.Include("sv_plugin.lua")
util.Include("sv_hooks.lua")
util.Include("cl_hooks.lua")

cwStorage.containerList = {
	["models/props_wasteland/controlroom_storagecloset001a.mdl"] = {8, "Storage Closet"},
	["models/props_wasteland/controlroom_storagecloset001b.mdl"] = {15, "Storage Closet"},
	["models/props_wasteland/controlroom_filecabinet001a.mdl"] = {4, "File Cabinet"},
	["models/props_wasteland/controlroom_filecabinet002a.mdl"] = {8, "File Cabinet"},
	["models/props_c17/suitcase_passenger_physics.mdl"] = {5, "Briefcase"},
	["models/props_junk/wood_crate001a_damagedmax.mdl"] = {8, "Wooden Crate"},
	["models/props_junk/wood_crate001a_damaged.mdl"] = {8, "Wooden Crate"},
	["models/props_interiors/furniture_desk01a.mdl"] = {4, "Desk"},
	["models/props_c17/furnituredresser001a.mdl"] = {10, "Dresser"},
	["models/props_c17/furnituredrawer001a.mdl"] = {8, "Drawer"},
	["models/props_c17/furnituredrawer002a.mdl"] = {4, "Drawer"},
	["models/props_c17/furniturefridge001a.mdl"] = {8, "Fridge"},
	["models/props_c17/furnituredrawer003a.mdl"] = {8, "Drawer"},
	["models/weapons/w_suitcase_passenger.mdl"] = {5, "Suitcase"},
	["models/props_junk/trashdumpster01a.mdl"] = {15, "Trash Dumpster"},
	["models/props_junk/wood_crate001a.mdl"] = {8, "Wooden Crate"},
	["models/props_junk/wood_crate002a.mdl"] = {10, "Wooden Crate"},
	["models/items/ammocrate_rockets.mdl"] = {15, "Large Crate"},
	["models/props_lab/filecabinet02.mdl"] = {8, "File Cabinet"},
	["models/items/ammocrate_grenade.mdl"] = {15, "Large Crate"},
	["models/props_junk/trashbin01a.mdl"] = {10, "Trash Bin"},
	["models/props_c17/suitcase001a.mdl"] = {8, "Suitcase"},
	["models/items/item_item_crate.mdl"] = {4, "Crate"},
	["models/props_c17/oildrum001.mdl"] = {8, "Barrel"},
	["models/items/ammocrate_smg1.mdl"] = {15, "Large Crate"},
	["models/items/ammocrate_ar2.mdl"] = {15, "Large Crate"},
	["models/props_junk/cardboard_box001a.mdl"] = {4, "Crate"},
	["models/props_junk/cardboard_box002a.mdl"] = {4, "Crate"},
	["models/props_junk/cardboard_box003a.mdl"] = {3, "Crate"},
	["models/props_wasteland/kitchen_fridge001a.mdl"] = {25, "Fridge"},
	["models/props_lab/partsbin01.mdl"] = {4, "Post box"},
	["models/props_office/file_cabinet_large_static.mdl"] = {25, "Large File Cabinet"},
	["models/props/cs_militia/footlocker01_closed.mdl"] = {15, "Footlocker"},
	["models/props_c17/furniturewashingmachine001a.mdl"] = {10, "Washing machine"},
	["models/props_c17/furniturestove001a.mdl"] = {10, "Stove"},
	["models/props_c17/lockers001a.mdl"] = {17, "Cabinet"},
	["models/props_wasteland/cargo_container01.mdl"] = {1000, "Cargo container"},
	["models/props_c17/briefcase001a.mdl"] = {6, "Briefcase"},
	["models/props_combine/breendesk.mdl"] = {10, "Table"},
	["models/props/cs_militia/crate_extrasmallmill.mdl"] = {15, "Crate"},
	["models/props/cs_militia/crate_extralargemill.mdl"] = {15, "Crate"},
	["models/props/cs_militia/crate_stackmill.mdl"] = {15, "Crate"},
	["models/props/cs_militia/dryer.mdl"] = {10, "Dryer"},
	["models/props_c17/furniturecupboard001a.mdl"] = {7, "Cupboard"},
	["models/props_borealis/bluebarrel001.mdl"] = {10, "Barrel"},
	["models/props_wasteland/kitchen_counter001c.mdl"] = {17, "Kitchen Table"},
	["models/props_junk/plasticbucket001a.mdl"] = {4, "Paint can"},
	["models/items/boxmrounds.mdl"] = {5, "Ammo Box"},
	["models/items/boxsrounds.mdl"] = {3, "Ammo Box"},
	["models/props/cs_assault/dryer_box.mdl"] = {8, "Crate"},
	["models/props/cs_assault/dryer_box2.mdl"] = {8, "Crate"},
	["models/props/cs_assault/washer_box.mdl"] = {8, "Crate"},
	["models/props/cs_assault/washer_box2.mdl"] = {8, "Crate"},
	["models/props/cs_assault/box_stack1.mdl"] = {20, "Boxes"},
	["models/props/cs_assault/box_stack2.mdl"] = {20, "Boxes"},
	["models/props/cs_assault/moneypallet_washerdryer.mdl"] = {17, "Boxes"},
	["models/props/cs_militia/stove01.mdl"] = {15, "Stove"},
	["models/props/cs_office/cardboard_box01.mdl"] = {8, "Crate"},
	["models/props/cs_office/cardboard_box02.mdl"] = {8, "Crate"},
	["models/props/cs_office/cardboard_box03.mdl"] = {8, "Crate"},
	["models/props/cs_office/file_cabinet1.mdl"] = {7, "Cabinet"},
	["models/props/cs_office/file_cabinet1_group.mdl"] = {20, "Cabinet"},
	["models/props/cs_office/file_cabinet2.mdl"] = {7, "Cabinet"},
	["models/props/cs_office/file_cabinet3.mdl"] = {7, "Cabinet"},
	["models/props/de_nuke/crate_extralarge.mdl"] = {200, "Crate"},
	["models/props/de_nuke/crate_extrasmall.mdl"] = {100, "Crate"},
	["models/props/de_nuke/crate_large.mdl"] = {150, "Crate"},
	["models/props/de_nuke/crate_small.mdl"] = {125, "Crate"},
	["models/props/de_nuke/file_cabinet1_group.mdl"] = {12, "Cabinet"},
	["models/props/de_prodigy/ammo_can_01.mdl"] = {30, "Ammo Crate Pallet"},
	["models/props/de_prodigy/ammo_can_02.mdl"] = {10, "Ammo Crate"},
	["models/props/de_prodigy/ammo_can_03.mdl"] = {60, "Large Ammo Crate Pallet"},
	["models/begotten/misc/lockbox.mdl"] = {50, "Lockbox"},
}