--[[
	Begotten III: Jesus Wept
	By: DETrooper, cash wednesday, gabs, alyousha35

	Other credits: kurozael, Alex Grist, Mr. Meow, zigbomb
--]]

config.ShareKey("use_opens_entity_menus")
config.ShareKey("target_id_delay")
config.ShareKey("additional_characters")
config.ShareKey("raised_weapon_system")
config.ShareKey("use_own_group_system")
config.ShareKey("default_inv_weight")
config.ShareKey("default_inv_space")
config.ShareKey("unrecognised_name")
config.ShareKey("enable_crosshair")
config.ShareKey("recognise_system")
config.ShareKey("max_chat_length")
config.ShareKey("use_free_aiming")
config.ShareKey("enable_heartbeat")
config.ShareKey("cash_enabled")
config.ShareKey("default_physdesc")
config.ShareKey("enable_vignette")
config.ShareKey("cash_weight")
config.ShareKey("cash_space")
--config.ShareKey("block_inv_binds")
config.ShareKey("fade_dead_npcs")
config.ShareKey("enable_headbob")
config.ShareKey("command_prefix")
config.ShareKey("default_flags")
config.ShareKey("minute_time")
config.ShareKey("local_voice")
config.ShareKey("talk_radius")
config.ShareKey("wages_name")
--config.ShareKey("door_cost")
config.ShareKey("enable_space_system")
--config.ShareKey("draw_intro_bars")
--config.ShareKey("show_business")
config.ShareKey("chat_multiplier")
config.ShareKey("enable_looc_icons")
config.ShareKey("block_cash_binds")
config.ShareKey("block_fallover_binds")
config.ShareKey("max_trait_points")