--[[
	Begotten III: Jesus Wept
	By: DETrooper, cash wednesday, gabs, alyousha35

	Other credits: kurozael, Alex Grist, Mr. Meow, zigbomb
--]]

config.Add("mysql_bans_table", "bans", nil, nil, true, true, true)
config.Add("mysql_characters_table", "characters", nil, nil, true, true, true)
config.Add("mysql_players_table", "players", nil, nil, true, true, true)
config.Add("mysql_username", "", nil, nil, true, true, true)
config.Add("mysql_password", "", nil, nil, true, true, true)
config.Add("mysql_database", "", nil, nil, true, true, true)
config.Add("mysql_host", "", nil, nil, true, true, true)
config.Add("mysql_port", 3306, nil, nil, true, true, true)
--config.Add("scale_attribute_progress", 1)
config.Add("messages_must_see_player", false, true)
--config.Add("default_attribute_points", 30, true)
config.Add("health_regeneration_enabled", true)
config.Add("enable_prop_protection", true)
config.Add("use_local_machine_date", false, nil, nil, nil, nil, true)
config.Add("use_local_machine_time", false, nil, nil, nil, nil, true)
config.Add("use_opens_entity_menus", true, true)
config.Add("shoot_after_raise_time", 1)
config.Add("save_recognised_names", true)
--config.Add("save_attribute_boosts", false)
config.Add("ragdoll_immunity_time", 0.5)
config.Add("additional_characters", 10, true)
config.Add("faction_ratio_enabled", true)
config.Add("change_class_interval", 180)
config.Add("raised_weapon_system", true, true)
config.Add("prop_kill_protection", true)
--config.Add("clockwork_intro_enabled", true)
config.Add("sprint_lowers_weapon", true)
config.Add("use_own_group_system", false, true)
config.Add("enable_gravgun_punt", true)
config.Add("default_inv_weight", 20, true)
config.Add("default_inv_space", 100, true)
config.Add("custom_weapon_color", true)
config.Add("save_data_interval", 666)
config.Add("damage_view_punch", true)
config.Add("enable_heartbeat", true, true)
config.Add("unrecognised_name", "Somebody you do not recognise.", true)
config.Add("scale_fall_damage", 1)
config.Add("enable_vignette", true, true)
config.Add("use_free_aiming", true, true, true)
config.Add("default_cash", 0, nil, nil, nil, nil, nil, true)
--config.Add("armor_chest_only", false)
config.Add("minimum_physdesc", 32, true)
config.Add("wood_breaks_fall", false)
config.Add("enable_crosshair", false, true, true)
config.Add("recognise_system", true, true)
config.Add("max_chat_length", 256, true, true)
config.Add("cash_enabled", true, true, nil, nil, nil, true)
config.Add("default_physdesc", "", true)
config.Add("scale_chest_dmg", 1)
config.Add("body_decay_time", 600)
config.Add("banned_message", "You are still banned for !t more !f.")
config.Add("wages_interval", 3600)
config.Add("scale_prop_cost", 0)
config.Add("fade_dead_npcs", true, true)
config.Add("cash_weight", 0, true)
config.Add("cash_space", 0, true)
config.Add("scale_head_dmg", 3)
--config.Add("block_inv_binds", true, true)
config.Add("target_id_delay", 0.5, true)
config.Add("scale_limb_dmg", 0.5)
config.Add("enable_headbob", true, true)
config.Add("command_prefix", "/", true)
config.Add("crouched_speed", 25)
config.Add("default_flags", "", true)
config.Add("disable_sprays", true)
config.Add("owner_steamid", "STEAM_0:0:0000000", nil, nil, true, true, true)
config.Add("hint_interval", 30)
config.Add("ooc_interval", 120)
config.Add("looc_interval", 5)
config.Add("global_ooc_enabled", false)
config.Add("minute_time", 60, true)
config.Add("voice_enabled", false)
config.Add("unlock_time", 3)
config.Add("local_voice", true, true)
config.Add("talk_radius", 384, true)
config.Add("wages_name", "Reaver Slave Drive", true)
config.Add("give_hands", true)
config.Add("give_keys", true)
config.Add("jump_power", 160)
config.Add("spawn_time", 60)
config.Add("walk_speed", 100)
config.Add("run_speed", 225)
--config.Add("door_cost", 10, true)
config.Add("lock_time", 2)
--config.Add("max_doors", 5)
config.Add("enable_space_system", false, true)
--config.Add("draw_intro_bars", true, true)
config.Add("enable_looc_icons", true, true, true)
--config.Add("show_business", true, true)
config.Add("chat_multiplier", true, true, true)
config.Add("enable_map_props_physgrab", false)
config.Add("entity_handle_time", 0.1)
--config.Add("quick_raise_enabled", true)
config.Add("block_cash_binds", true, true)
config.Add("block_fallover_binds", false, true)
config.Add("max_trait_points", 0, true);