--[[
	BEGOTTEN III: Developed by DETrooper, cash wednesday, gabs & alyousha35
--]]

TYPING_RAISE = 7
TYPING_WHISPER = 6
TYPING_PERFORM = 5
TYPING_NORMAL = 4
TYPING_RADIO = 3
TYPING_YELL = 2
TYPING_OOC = 1;